webpack-dev-server導入 #78
hr-js/sta_access_manager pull request #88
Opened 2018-02-22 12:48 UTC by ikkyu-3

## 該当issue
- webpack-dev-server導入 #78

## 実装の内容
- webpack-dev-serverをinstall
- webpack.config.jsにwebpack-dev-serverを使用して、live reloadできるように設定
- webpack-dev-serverで起動できるようにpackage.jsonのscriptを変更
- Reactで表示できるようにjsxファイルを作成
- 静的なファイルで起動する設定のためindex.htmlファイルを作成(pugは使用しないように変更するつもりでいます)

## 確認内容
- 動作確認
- webpack.config.jsの設定

以上です。
よろしくお願いします。

2018-02-22 13:26 UTC, ta-chibana requested changes
コメントしました 🙋

2018-02-22 13:26 UTC, ta-chibana commented on package.json
> +    "start": "npm run build_client & npm run build_server && node ./bin/www",
変わっちゃってます

2018-02-22 13:26 UTC, ta-chibana commented on package.json
> +    "build_client": "webpack-dev-server --open",
実際にビルド成果物ができたりするわけではないので `build_client` でなく `start:client` とかが適切だと思いました！
[webpack.config.js](https://github.com/hr-js/sta_access_manager/pull/88/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dR15) で `open` オプション指定されているのでこちらは不要そうです。

2018-02-22 13:26 UTC, ta-chibana commented on webpack.config.js
> +        test: /\.js[x]?$/,
元のままでも良かったと思いますよ！

2018-02-22 15:23 UTC, ikkyu-3 commented on package.json
> +    "build_client": "webpack-dev-server --open",
確かに！ありがとうございます。参考になりました！

2018-02-22 15:33 UTC, ikkyu-3 commented on package.json
> +    "start": "npm run build_client & npm run build_server && node ./bin/www",
ここなんですが、`&&`だとwebpackはwatchしてるので、`npm run build_server` の処理が始まらないようです。なので、`&`に変更しました。

以下を参考にしてみました。
[Linuxコマンドを連続して使うには - Qiita](https://qiita.com/egawa_kun/items/714394609eef6be8e0bf)

2018-02-22 15:41 UTC, ta-chibana commented on package.json
> +    "start": "npm run build_client & npm run build_server && node ./bin/www",
そもそも `start` でクライアント側はビルドしないようにして、dev-serverに任せるようにすれば良いのではないですか？

2018-02-22 15:46 UTC, ikkyu-3 commented on webpack.config.js
> +        test: /\.js[x]?$/,
わかりやすさって思いましたが。。

[正規表現の構文](https://msdn.microsoft.com/ja-jp/library/cc392020.aspx)
ここを見ると`[]`の使い方的にスッキリしないですね。

元に戻そうと思います。

2018-02-23 00:08 UTC, krhrtky commented
npm script のkeyの命名規則をよく知らないのですが。。

- :(コロン)でつなげたもの `start:build`

- スネークケース `build_client`

が共存しているのが、違和感に感じました。

2018-02-24 06:57 UTC, ta-chibana commented
![LGTM](http://www.lgtm.in/p/I6clAmRYp)

2018-02-24 07:00 UTC, tankette148 commented
内容確認しました！

2018-02-24 07:02 UTC, merged